- name: Install apt packages
  become: true
  apt:
    name:
    - apt-transport-https
    - bat
    - build-essential
    - ca-certificates
    - cmake
    - curl
    - default-jdk
    - exa
    - fd-find
    - fzf
    - gettext
    - git
    - gnupg
    - htop
    - lsb-release
    - ninja-build
    - npm
    - python3
    - python3-pip
    - python3-venv
    - ripgrep
    - software-properties-common
    - tmux
    - tree
    - unzip
    - wget
    - xclip
    - zsh
