- name: Install apt packages
  become: true
  apt:
    name:
    - build-essential
    - software-properties-common
    - git
    - cmake
    - ninja-build
    - curl
    - wget
    - apt-transport-https
    - zsh
    - tmux
    - fd-find
    - htop
    - tree
    - unzip
    - gettext
    - npm
    - xclip
    - ripgrep
    - fd-find
    - fzf
    - python3
    - python3-pip
    - python3-venv
    - default-jdk
    - exa
    - bat
    - podman
