- name: Copy pref file to correct location
  ansible.builtin.copy:
    src: ../resources/99microsoft-dotnet.pref
    dest: /etc/apt/preferences.d/

- name: Install dotnet sdk's
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
    name:
    - dotnet-sdk-6.0
    - dotnet-sdk-7.0
