- name: Setup Azure core tools repo
  become: true
  script: ../scripts/setup-microsoft-feed.sh

- name: Install dotnet sdk's
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
    name:
    - dotnet-sdk-7.0
    - dotnet-sdk-8.0
