- name: Cloning Neovim repo
  shell: git clone https://github.com/neovim/neovim.git neovim
  args:
    chdir: /home/nige/projects/external/neovim
    creates: /home/nige/projects/external/neovim 


- name: Updating Neovim repo
  shell: git pull
  args:
    chdir: /home/nige/projects/external/neovim

- name: Build Neovim
  make:
    chdir: /home/nige/projects/external/neovim
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo


- name: Install Neovim
  become: true
  make:
    chdir: /home/nige/projects/external/neovim
    target: install


