- name: Install NPM
  become: true
  apt:
    name:
    - npm

- name: Install N
  become: true 
  npm:
    name: n
    global: yes

- name: Install correct version of Node
  become: true
  shell: n latest

- name: Install Yarn
  become: true
  npm:
    name: yarn
    global: yes


- name: Install tsc
  become: true
  npm:
    name: tsc
    global: yes

