- hosts: localhost
  vars:

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present

  tasks:
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/oh-my-zsh.yml
    - include_tasks: tasks/dotnet.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/powershell.yml
    - include_tasks: tasks/azure-utils.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/bicep-lsp.yml
    - include_tasks: tasks/curlie.yml
    - include_tasks: tasks/git-delta.yml
    - include_tasks: tasks/git-config.yml

